"""empty message

Revision ID: 0b1f23752e23
Revises: 1f42cb4959a8
Create Date: 2025-02-06 21:15:44.207885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b1f23752e23'
down_revision: Union[str, None] = '1f42cb4959a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'agreedPrice',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('bookings', 'agreed_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('agreed_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('bookings', 'agreedPrice',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
