"""empty message

Revision ID: 0c51fa51ca42
Revises: bfc28994c03d
Create Date: 2025-02-05 12:12:43.307938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c51fa51ca42'
down_revision: Union[str, None] = 'bfc28994c03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('firstName', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('bookings', sa.Column('lastName', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('bookings', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('bookings', sa.Column('phoneNumber', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('bookings', sa.Column('agreed_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'agreed_price')
    op.drop_column('bookings', 'phoneNumber')
    op.drop_column('bookings', 'email')
    op.drop_column('bookings', 'lastName')
    op.drop_column('bookings', 'firstName')
    # ### end Alembic commands ###
