"""empty message

Revision ID: 1f42cb4959a8
Revises: a148995b43ef
Create Date: 2025-02-06 20:59:23.810883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f42cb4959a8'
down_revision: Union[str, None] = 'a148995b43ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('agreedPrice', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'agreedPrice')
    # ### end Alembic commands ###
